name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --manifest-path api/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path api/Cargo.toml
  
  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --manifest-path frontend/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path frontend/Cargo.toml
